#pragma once

namespace VTuberKitForNative {

static const char* CubismEffect_fx = 
"cbuffer ConstantBuffer {\n"
"    float4x4 projectMatrix;\n"
"    float4x4 clipMatrix;\n"
"    float4 baseColor;\n"
"    float4 multiplyColor;\n"
"    float4 screenColor;\n"
"    float4 channelFlag;\n"
"}\n"
"\n"
"Texture2D mainTexture : register(t0);\n"
"SamplerState mainSampler : register(s0);\n"
"Texture2D maskTexture : register(t1);\n"
"\n"
"// Vertex shader input\n"
"struct VS_IN {\n"
"    float2 pos : POSITION;\n"
"    float2 uv : TEXCOORD0;\n"
"};\n"
"\n"
"// Vertex shader output\n"
"struct VS_OUT {\n"
"    float4 Position : SV_POSITION;\n"
"    float2 uv : TEXCOORD0;\n"
"    float4 clipPosition : TEXCOORD1;\n"
"};\n"
"\n"
"\n"
"// Mask shader\n"
"VS_OUT VertSetupMask(VS_IN In) {\n"
"    VS_OUT Out = (VS_OUT)0;\n"
"    Out.Position = mul(float4(In.pos, 0.0f, 1.0f), projectMatrix);\n"
"    Out.clipPosition = mul(float4(In.pos, 0.0f, 1.0f), projectMatrix);\n"
"    Out.uv.x = In.uv.x;\n"
"    Out.uv.y = 1.0f - +In.uv.y;\n"
"    return Out;\n"
"}\n"
"\n"
"float4 PixelSetupMask(VS_OUT In) : SV_Target{\n"
"    float isInside =\n"
"    step(baseColor.x, In.clipPosition.x / In.clipPosition.w)\n"
"    * step(baseColor.y, In.clipPosition.y / In.clipPosition.w)\n"
"    * step(In.clipPosition.x / In.clipPosition.w, baseColor.z)\n"
"    * step(In.clipPosition.y / In.clipPosition.w, baseColor.w);\n"
"    return channelFlag * mainTexture.Sample(mainSampler, In.uv).a * isInside;\n"
"}\n"
"\n"
"// Vertex shader\n"
"// normal\n"
"VS_OUT VertNormal(VS_IN In) {\n"
"    VS_OUT Out = (VS_OUT)0;\n"
"    Out.Position = mul(float4(In.pos, 0.0f, 1.0f), projectMatrix);\n"
"    Out.uv.x = In.uv.x;\n"
"    Out.uv.y = 1.0f - +In.uv.y;\n"
"    return Out;\n"
"}\n"
"\n"
"// masked\n"
"VS_OUT VertMasked(VS_IN In) {\n"
"    VS_OUT Out = (VS_OUT)0;\n"
"    Out.Position = mul(float4(In.pos, 0.0f, 1.0f), projectMatrix);\n"
"    Out.clipPosition = mul(float4(In.pos, 0.0f, 1.0f), clipMatrix);\n"
"    Out.uv.x = In.uv.x;\n"
"    Out.uv.y = 1.0f - In.uv.y;\n"
"    return Out;\n"
"}\n"
"\n"
"// Pixel Shader\n"
"// normal\n"
"float4 PixelNormal(VS_OUT In) : SV_Target{\n"
"    float4 texColor = mainTexture.Sample(mainSampler, In.uv);\n"
"    texColor.rgb = texColor.rgb * multiplyColor.rgb;\n"
"    texColor.rgb = (texColor.rgb + screenColor.rgb) - (texColor.rgb * screenColor.rgb);\n"
"    float4 color = texColor * baseColor;\n"
"    color.xyz *= color.w;\n"
"    return color;\n"
"}\n"
"\n"
"// normal premult alpha\n"
"float4 PixelNormalPremult(VS_OUT In) : SV_Target{\n"
"    float4 texColor = mainTexture.Sample(mainSampler, In.uv);\n"
"    texColor.rgb = texColor.rgb * multiplyColor.rgb;\n"
"    texColor.rgb = (texColor.rgb + screenColor.rgb * texColor.a) - (texColor.rgb * screenColor.rgb);\n"
"    float4 color = texColor * baseColor;\n"
"    return color;\n"
"}\n"
"\n"
"// masked\n"
"float4 PixelMasked(VS_OUT In) : SV_Target{\n"
"    float4 texColor = mainTexture.Sample(mainSampler, In.uv);\n"
"    texColor.rgb = texColor.rgb * multiplyColor.rgb;\n"
"    texColor.rgb = (texColor.rgb + screenColor.rgb) - (texColor.rgb * screenColor.rgb);\n"
"    float4 color = texColor * baseColor;\n"
"    color.xyz *= color.w;\n"
;

static const char* CubismEffect_fx_part2 = 
"    float4 clipMask = (1.0f - maskTexture.Sample(mainSampler, In.clipPosition.xy / In.clipPosition.w)) * channelFlag;\n"
"    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
"    color = color * maskVal;\n"
"    return color;\n"
"}\n"
"\n"
"// masked inverted\n"
"float4 PixelMaskedInverted(VS_OUT In) : SV_Target{\n"
"    float4 texColor = mainTexture.Sample(mainSampler, In.uv);\n"
"    texColor.rgb = texColor.rgb * multiplyColor.rgb;\n"
"    texColor.rgb = (texColor.rgb + screenColor.rgb) - (texColor.rgb * screenColor.rgb);\n"
"    float4 color = texColor * baseColor;\n"
"    color.xyz *= color.w;\n"
"    float4 clipMask = (1.0f - maskTexture.Sample(mainSampler, In.clipPosition.xy / In.clipPosition.w)) * channelFlag;\n"
"    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
"    color = color * (1.0f - maskVal);\n"
"    return color;\n"
"}\n"
"\n"
"// masked premult alpha\n"
"float4 PixelMaskedPremult(VS_OUT In) : SV_Target{\n"
"    float4 texColor = mainTexture.Sample(mainSampler, In.uv);\n"
"    texColor.rgb = texColor.rgb * multiplyColor.rgb;\n"
"    texColor.rgb = (texColor.rgb + screenColor.rgb * texColor.a) - (texColor.rgb * screenColor.rgb);\n"
"    float4 color = texColor * baseColor;\n"
"    float4 clipMask = (1.0f - maskTexture.Sample(mainSampler, In.clipPosition.xy / In.clipPosition.w)) * channelFlag;\n"
"    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
"    color = color * maskVal;\n"
"    return color;\n"
"}\n"
"\n"
"// masked inverted premult alpha\n"
"float4 PixelMaskedInvertedPremult(VS_OUT In) : SV_Target{\n"
"    float4 texColor = mainTexture.Sample(mainSampler, In.uv);\n"
"    texColor.rgb = texColor.rgb * multiplyColor.rgb;\n"
"    texColor.rgb = (texColor.rgb + screenColor.rgb * texColor.a) - (texColor.rgb * screenColor.rgb);\n"
"    float4 color = texColor * baseColor;\n"
"    float4 clipMask = (1.0f - maskTexture.Sample(mainSampler, In.clipPosition.xy / In.clipPosition.w)) * channelFlag;\n"
"    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
"    color = color * (1.0f - maskVal);\n"
"    return color;\n"
"}\n"
;

}
